### ISSUE TITLE
Add cake-contrib user on NuGet.org

### ISSUE THREAD

**Issue by gep13** [agc93/Cake.ViewCompiler#2]
@agc93  First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this for Cake.ViewCompiler? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by agc93** [comment]
Good call. I'm clearly not going to get the time to redo this properly, so I'll add this when I get a chance :)

**Comment by gep13** [comment]
@agc93 just wanted to follow up to see if you had had a chance to give this some thought.  Thanks!

**Comment by gep13** [comment]
@agc93 nudge 😄

**Comment by agc93** [comment]
Added cake-contrib user on NuGet.org

Will transfer GH org when I (eventually) get around to redoing this properly

**Comment by gep13** [comment]
The latter is not a requirement, the cake-contrib user is the main thing, but if you want to move it in, then I am happy to accept it.
